### ISSUE TITLE
Rebuild behaviour

### ISSUE THREAD

**Issue by 2maz** [rock-core/autoproj#78] opened 2015-06-09 07:33 UTC
Autoproj does not cleanup, i.e. remove the install folder anymore when doing a rebuild of all packages.

**Comment by doudou** [comment] 2015-06-09 17:32
I believe that it never did. Should it ?

**Comment by goldhoorn** [comment] 2015-06-10 07:34
It does in the past. I think it should do. Because there might be dead projects in it. 
e.G. the dependencies are not correct and some users starts a component then the typekits might be 
incompatible. If the package is missing after a full rebuild the error get's clearer instead
of give the user the impression that "rock itself is inconsistent"

**Comment by 2maz** [comment] 2015-06-10 15:18
We get quite some "side-effects/inconsistencies" which are hard to track down if not cleaning up -- that is why rebuilding "solved" many issues in the past.

**Comment by doudou** [comment] 2015-06-10 15:32
The problem is the following:
 - it assumes that people did not compile anything by hand
 - it can be done only when rebuilding all

I would be OK with asking for it, though (the same place we ask whether the user really wants to rebuild all packages)

**Comment by 2maz** [comment] 2015-06-10 15:52
Not clear to me why it assumes that people did not compile anything by hand?

Autoproj did clear the install folder in the past even without asking, though I am right now not able to tell when this behaviour stopped doing this or if that was a sideeffect.
However, clearly requesting permission for it and performing cleanup would improve the process.

**Comment by doudou** [comment] 2015-06-10 15:56
> Not clear to me why it assumes that people did not compile anything by hand?

Because if you delete the install folder then these parts will not get reinstalled automatically

**Comment by doudou** [comment] 2015-11-03 13:18
Unless one of you plan on adding the relevant functionality, I'll close this.

**Comment by doudou** [comment] 2016-03-29 14:23
> Unless one of you plan on adding the relevant functionality, I'll close this.

I guess the answer to this question was "no". So, closing.

**Closed by doudou** 2016-03-29 14:23 UTC
