### ISSUE TITLE
initial import fails if python packages are used, but python is not installed

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#240] opened 2019-02-19 12:10 UTC
It looks like "python" is called by autobuild before the osdeps are installed

```
building initial autoproj import log, this may take a while
/usr/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - python (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /root/.local/share/autoproj/gems/ruby/2.3.0/gems/autobuild-1.17.0/lib/autobuild/packages/python.rb:53:in `python_path'
	from /root/.local/share/autoproj/gems/ruby/2.3.0/gems/autobuild-1.17.0/lib/autobuild/packages/python.rb:89:in `update_environment'
```

**Comment by g-arjones** [comment] 2019-02-19 12:16
It is indeed... Could you please try to add `python` as a dependency in the manifest? If that works, we could do that for python_package here: 

https://github.com/rock-core/autoproj/blob/6ae7ff7a65c98a2bf9bf2536a0d1d6f0ad01a982/lib/autoproj/autobuild_extensions/dsl.rb#L167

**Comment by planthaber** [comment] 2019-02-19 16:18
tried it by installing python-dev beforehand (tested in docker) and it worked.

I'll re-run it with python in manifest

**Comment by planthaber** [comment] 2019-02-19 16:37
it doesn't work in the manifest, I guess the initial osdeps run is after the initial import phase

**Comment by g-arjones** [comment] 2019-02-19 16:40
Yeah.. The problem is that Package#update_environment is called after each import but osdeps are installed only after all packages have been imported.. Not sure if there's a easy fix for this..

**Comment by planthaber** [comment] 2019-02-20 08:46
I guess the only way would be to make python a dependency of autobuild. But i wouldn't do that.

What about  not raising en exception, but only print a warning here:

https://github.com/rock-core/autobuild/blob/master/lib/autobuild/packages/python.rb#L55

**Comment by doudou** [comment] 2019-02-20 12:14
> Yeah.. The problem is that Package#update_environment is called after each import but osdeps are installed only after all packages have been imported.. Not sure if there's an easy fix for this..

The package managers can re-update the environment after the osdeps have run - this is what the bundler handler does for instance.

In principle, we could either
- accept that "no python" == "no python environment" and ignore the error
- add a "dependent osdeps" stage in all package managers, and have autoproj install these osdeps before the import. This is how the importers are installed on-demand already.

**Comment by doudou** [comment] 2019-02-21 11:53
>     * add a "dependent osdeps" stage in all package managers, and have autoproj install these osdeps before the import. This is how the importers are installed on-demand already.

Actually, this already exists: 3d3c73310e42d0bd2317b6c49dfce5d74d8bff05. I'm not sure when these are installed, but we could move it to before the update instead of after.

**Comment by g-arjones** [comment] 2019-02-21 12:17
Not sure I am following.. This issue is about source packages, not package-managed packages. Package managers dependencies are installed on-demand (if there are osdeps that require them) and just prior to the osdeps phase (just prior to their usage).

I think the soliution to this is more like what is done to install VCS packages:

https://github.com/rock-core/autoproj/blob/ebc72e17e146d8083ee96060a8da9f2cfd86082c/lib/autoproj/ops/import.rb#L128

Maybe adding "internal_dependencies" to `Autobuild::Package` subclasses

**Comment by doudou** [comment] 2019-02-21 13:21
> This issue is about source packages, not package-managed packages.

Oh yes, misread the issue, sorry. What you suggest would make sense.

**Closed** 2019-02-27 13:53 UTC
