### ISSUE TITLE
autoproj2.0.0.rc15: cannot find bundler during upgrade

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#103] opened 2015-11-18 12:58 UTC
cannot find 'bundler' in PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/aduda/.gem/ruby/2.0.0/bin
    installing it now ...
    Detected 'gem' to be /usr/bin/gem
    ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-document
    FATAL: failed to install bundler in /home/aduda/dev/wally/.autoproj
      it appears that you already have some autoproj-generated env.sh loaded
      - if you are running 'autoproj upgrade', please contact the autoproj author at https://github.com/rock-core/autoproj/issues/new
      - if you are running an install, try again in a console where the env.sh is not loaded

calling 'which bundler' on the command line returns:
  
    /home/aduda/dev/wally/.gems/bin/bundler

Workaround is to globally install bundler

**Comment by doudou** [comment] 2015-11-22 15:10
$HOME/.gems is not a standard location for gems. Autoproj 2.0 ignores it on purpose, ESPECIALLY since the way you use it it's not versioned.

Ruby 2.0 seems to not know about `--no-document` ... :(

**Comment by doudou** [comment] 2015-11-22 15:16
> Ruby 2.0 seems to not know about --no-document ... :(

Actually, it does. ruby 2.0 shipped with gem 2.0.14. Maybe it's bad detection of the 'gem' program. Is it system (ubuntu package) install ? Should autoproj call gem2.0 instead of gem ?

**Comment by D-Alex** [comment] 2015-11-25 10:40
I am moving all machines to the new autoproj version. I will report if I got the problem again and try to debug it.

**Comment by D-Alex** [comment] 2015-11-25 13:48
second machine same problem. I guess autoproj tires to install it in /usr/.. and is not allowed to do so. Maybe autoproj should just use my_project/.gems until the upgrade is finished. 

    autoproj upgrade
    cannot find 'bundler' in PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/aduda/.gem/ruby/2.0.0/bin
    installing it now ...
    Detected 'gem' to be /usr/bin/gem
    ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-document
    FATAL: failed to install bundler in /home/aduda/dev/wally/.autoproj
     it appears that you already have some autoproj-generated env.sh loaded
     - if you are running 'autoproj upgrade', please contact the autoproj author at https://github.com/rock-core/autoproj/issues/new
     - if you are running an install, try again in a console where the env.sh is not loaded
    aduda@ROBEX:~/dev/wally$ which bundler
    /home/aduda/dev/wally/.gems/bin/bundler

**Comment by doudou** [comment] 2015-11-25 15:03
The problem is `invalid option: --no-document`. It tries to run /usr/bin/gem which on your system probably is ruby 1.9's gem (which does not have `--no-document`). A possible fix is to explicitely use Gem.ruby to run the gem program.

You can try to add Gem.ruby before gem_program in autoproj/ops/install.rb:234

**Comment by doudou** [comment] 2015-11-25 15:09
It seems you're using 'autoproj upgrade'. How did you start doing that ? (I checked and it does not seem to be mentioned in the email). The "supported" method is to run autoproj_install

**Comment by D-Alex** [comment] 2015-11-25 15:22
It all started because of https://github.com/rock-core/rock-package_set/issues/94. Here, I was not aware of any email you sent. Using the mentioned workarounds it seems to work.

* gem install autoproj --prerelease 
* autoproj build                             # gives an error see https://github.com/rock-core/autoproj/pull/104
* autoproj upgrade                       # gives an error see https://github.com/rock-core/autoproj/issues/103
* sudo gem install bundler           # in a new console
* autoproj upgrade                       
* touch .autoproj/env.sh               # workaround env.sh
* autoproj clean
* autoproj build -k

**Comment by doudou** [comment] 2016-03-29 14:16
The detection of 'gem' got hardened quite a bit. I can't reproduce this in all my upgrade tests, so I'm closing it.

**Closed by doudou** 2016-03-29 14:16 UTC
