### ISSUE TITLE
`Autoproj.manifest.main_package_set` is available later than expected

### ISSUE THREAD

**Issue by moooeeeep** [rock-core/autoproj#360] opened 2021-12-15 15:30 UTC
We've stumbled accross another inconsistency between the behavior of the current release version (2.15) and current master.

Consider this buildconf: https://github.com/moooeeeep/buildconf_3

With the current release bootstrap `Autoproj.manifest.main_package_set` is available while the `init.rb` of the package set is run. With the dev bootstrap `nil` is returned in the package set. It is later available in the `overrides.rb` of the buildconf though.

---

The interesting part of the output:

Release version:

    p1/init.rb: is good
    buildconf/overrides: is good

Dev version:

    p1/init.rb: is nil
    buildconf/overrides: is good

Not sure if this is some internal API which is subject to change without notice. But one of our package sets appears to use it, which is now broken with the dev version.

**Comment by g-arjones** [comment] 2021-12-15 15:48
Duplicate of https://github.com/rock-core/autoproj/issues/354

**Comment by moooeeeep** [comment] 2021-12-15 15:52
Thanks for pointing me to that! I think we refer to the same problem.

**Comment by doudou** [comment] 2022-02-24 00:01
On top of being a duplicate, is has been fixed by #369

**Closed by doudou** 2022-02-24 00:01 UTC
