### ISSUE TITLE
autoproj commit for package selection

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#46] opened 2015-02-16 11:40 UTC
when I do autoproj version for a package selection, e.g.
`autoproj versions base/types`
I get a list of package. However, when I try the same thing for commit
`autoproj commit base/types`
I get 
`error: pathspec 'base/types' did not match any file(s) known to git.`

**Comment by doudou** [comment] 2015-02-17 17:37
autoproj-commit is currently very bare-bone and passes its arguments to git commit. This is a duplicate of #42

**Closed by doudou** 2015-02-17 17:37 UTC
Labels: post-versioning
