### ISSUE TITLE
Incompatible with new versions of bundler

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#214] opened 2018-09-04 09:47 UTC
It seems like autoprojs way of calling bundler is failing with newer versions. Bundler seems to check its binstubs to be original, but autoproj is adding a preamble to them

Your `bin/bundle` was not generated by Bundler, so this binstub cannot run.
Replace `bin/bundle` by running `bundle binstubs bundler --force`, then run this command again.

It looks like the Autoproj generated preamble in .autoproj/bin/bundle is causing this error ans makes autoproj unusable.

Nevertheless, removing the lines or just moving them, makes it work again.

So when the generated preable starts after the original comments in the bundle file, it works.

https://github.com/rock-core/autoproj/blob/master/lib/autoproj/ops/install.rb#L405
 should start at line 10.

Ugly Workaround:
Change the line in the following file location: `~/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.8.3/lib/autoproj/ops/install.rb` or whatever autoproj/ruby version you are using)
```ruby
script_lines.insert(1, <<-RESTART_BUNDLER)
script_lines.insert(10, <<-RESTART_BUNDLER)
```

But this is just a workaround, as the layout of the bundle file may change in future.

**Comment by planthaber** [comment] 2018-09-04 09:51
To make the workaround work, you have to edit ./autoproj/bin/bundle manually and move the autoproj injected code:

```ruby
# Autoproj generated preamble
if defined?(Bundler)
    Bundler.with_clean_env do
        exec($0, *ARGV)
    end
end
ENV['BUNDLE_GEMFILE'] ||= '/home/dfki.uni-bremen.de/planthaber/dfki/rock/cdff/.autoproj/Gemfile'
```
after the initial comments or just remove them completely

**Comment by m0rsch1** [comment] 2018-09-04 11:07
So, what are the steps?
* Remove autoproj generated preamble from .autoproj/bin/bundler
* In .autproj/bin/bundler execute `bundle binstubs bundler --force`
And then it should work? For me it does not unfortunately.

**Comment by m0rsch1** [comment] 2018-09-04 11:08
This is what I get

$ aup
  operating system: debian - 9,stretch
  updating bundler
Command failed
autoproj: failed in osdeps phase
    '/home/taste/esrocos_workspace/.autoproj/bin/bundle show autoproj' returned status 42
    see /home/taste/esrocos_workspace/install/log/autoproj-osdeps.log for details
    last 5 lines are:

    Activating bundler (< 2) failed:
    Could not find 'bundler' (< 2) among 13 total gem(s)
    Checked in 'GEM_PATH=/home/taste/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/i386-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
    
    To install the version of bundler this project requires, run `gem install bundler -v '< 2'`

**Comment by planthaber** [comment] 2018-09-04 13:26
The steps are as described above:

* Remove autoproj generated preamble from .autoproj/bin/bundler
* edit ~/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.8.3/install.rb and replace 
```ruby
script_lines.insert(1, <<-RESTART_BUNDLER)
```
with
```ruby
script_lines.insert(10, <<-RESTART_BUNDLER)
```
* run aup

**Comment by planthaber** [comment] 2018-09-04 14:48
yeah, it is the file linked in the first post:

`~/.autoproj/gems/ruby/2.5.0/gems/autoproj-2.8.3/lib/autoproj/ops/install.rb`

Be sure to uset the correct autoproj version number in the path.

**Comment by doudou** [comment] 2018-09-04 16:12
... triggered by having a BUNDLE_GEMFILE that is longer ...

I'll just re-add the comment Bundler expects at the top of the stub file

**Comment by doudou** [comment] 2018-09-04 16:19
Should be fixed by 2.8.4 ... thanks for reporting

**Comment by g-arjones** [comment] 2018-09-04 16:33
I believe these are two unrelated issues.. The problem @m0rsch1 is having is due to the removal of proper `GEM_HOME` env var setup in the shims.

```
➜  autoproj_test env -i .autoproj/bin/bundle show autoproj
Activating bundler (< 2) failed:
Could not find 'bundler' (< 2) among 56 total gem(s)
Checked in 'GEM_PATH=/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information

To install the version of bundler this project requires, run `gem install bundler -v '< 2'`
```

**Comment by doudou** [comment] 2018-09-04 16:48
> The problem @m0rsch1 is having is due to the removal of proper GEM_HOME env var setup in the shims.

True ... and 2.8.5 (I just pushed) is fixing that one

@m0rsch1 the problem is that you need autoproj to update autoproj. The best workaround to get a working setup is to install bundler manually with

```
gem install --user bundler
```

**Comment by g-arjones** [comment] 2018-09-04 16:52
@doudou Why not keep these setup in the shims themselves? That commit isn't really fixing them...

**Comment by doudou** [comment] 2018-09-04 17:38
> Why not keep this setup in the shims themselves? That commit isn't really fixing them...

Not sure what "this setup in the shims themselves" mean, really.

**Comment by g-arjones** [comment] 2018-09-04 17:39
Just opened a PR...

**Closed** 2018-09-04 17:40 UTC

**Comment by m0rsch1** [comment] 2018-09-05 07:26
It works :) Thanks a lot.
